language: csharp
solution: CompuMaster.Text.Diff.sln

#before_install:
#  - nuget install NUnit.Runners -Version 3.10.0 -OutputDirectory testrunner

install:
  - nuget restore CompuMaster.Text.Diff.sln

script:
  - msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:PostBuildEvent="" CompuMaster.Text.Diff.sln
#  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./CompuMaster.Test.Text.Diff/bin/CompuMaster.Test.Text.Diff.dll